[project]
name = "tdt4120-algoritmer-og-datastrukturer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "August Hauge Smevold", email = "august.hauge.smevold@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
tdt4120-algoritmer-og-datastrukturer = "tdt4120_algoritmer_og_datastrukturer:main"

[build-system]
requires = ["uv_build>=0.12.8,<0.13.0"]
build-backend = "uv_build"
